### ISSUE TITLE
Chrome: "busy" value throwing error that "e.match is not a function"

### ISSUE THREAD

**Issue by brian-weasner** [SjonHortensius/3v4l_org#12]
When loading <https://3v4l.org/#live> I'm presented with the editor that simply says "busy" and fails to complete loading and allow editing.

![image](https://github.com/user-attachments/assets/83518155-2b1e-4400-8eaf-a99760aef9b5)

Errors are present in the inspector console.
```plaintext
ace.js:1 Uncaught TypeError: e.match is not a function
    at e.$detectNewLine (ace.js:1:130669)
    at e.insert (ace.js:1:132467)
    at e.setValue (ace.js:1:130435)
    at e.setValue (ace.js:1:247773)
    at Object.externalMessage (c.e1ace675.js:3:4860)
```

Browsers Tested:
- Fails on:
  - Chrome (126.0.6478.127 & 126.0.6478.183)
  - Vivaldi (6.8.3381.46)
- Works on:
  - Microsoft Edge:  (126.0.2592.102)
  - Firefox (128.0)

**Comment by SjonHortensius** [comment]
Thanks for the extensive report. I've deployed a hotfix by disabling the `externalMesage` method, can you confirm this fixes this issue?

**Comment by brian-weasner** [comment]
It has been fixed! Thank you!

**Comment by SjonHortensius** [comment]
fixed in https://github.com/SjonHortensius/3v4l_org/commit/693a4e802e00881aa4e980ff82c209593c0ab463
