### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by homersimpsons** [SjonHortensius/3v4l_org#14]
I wanted to tackle #8, but I have a hard time setting up the project.

I started to create a [`compose.yaml`](https://docs.docker.com/compose/) file to set up the project, I have the following issues:
- [x] `dbDsn` for the flag `--dsn` is hard to get right:
  - I could find a documentation on it (there are [3 go driver for postgres](https://go.dev/wiki/SQLDrivers)), it seems we are using https://pkg.go.dev/github.com/lib/pq
  - I currently have `postgres://postgres:postgres@postgresql/postgres` (the database name is hardcoded in structure.sql, but the schema is not)
- [x] There are a lot of components to set up: postgresql, golang, php-fpm, memcached and nginx (docker setup)
  - [x] Their versions is not specified, "recent versions" should work according to https://github.com/SjonHortensius/3v4l_org/issues/14#issuecomment-2244717217
  - [x] I have `failed to ping db: pq: unknown authentication response: 10`, I used `POSTGRES_HOST_AUTH_METHOD: password`
  - [x] It is unclear if there is any specific configuration for memcached, it looks like there is nothing to do beside having it installed
  - [x] `library/` and `htdocs/` are both at the root, so we have to embed everything in both nginx and php-fpm (for now the project structure will remain as-is)
- [x] Once everything is kind of set up, `Basic::` is not defined, how to setup this? there is no `composer.json`? Should I copy-paste the entire framework somewhere? There are no instructions in https://github.com/SjonHortensius/Basic_Framework nor in this repository (discussions in https://github.com/SjonHortensius/3v4l_org/pull/15#discussion_r1690139650)
  - It looks like the sources are expected to be in `/srv/http/.common/Basic_Framework`
 - [x] The project requires the following php extensions: memcached, pdo, pdo_pgsql, gmp
 - [x] It is not possible to define an external memcache in `config.ini` (fixed https://github.com/SjonHortensius/Basic_Framework/commit/804c4d2d4a4253650286c2261267233781826b24):
   1. Basic_Framework loads the cache https://github.com/SjonHortensius/Basic_Framework/blob/758bf59306334dcf756c33217b8ad3f3d93f31a0/library/Basic.php#L44
   2. Basic_Framework needs the config https://github.com/SjonHortensius/Basic_Framework/blob/758bf59306334dcf756c33217b8ad3f3d93f31a0/library/Basic/Memcache.php#L16, at this point it is empty so it will use the "localhost:11211" memcache instance which does not exist
   3. Basic_Framework needs the cache https://github.com/SjonHortensius/Basic_Framework/blob/758bf59306334dcf756c33217b8ad3f3d93f31a0/library/Basic/Config.php#L23, accessing the memcache instance will fail here
- [x] It looks like a `/in/` directory should be shared between the daemon and the website: It works fine with tmpfs.
- [x] The deamon need access to postgres' socket: It works fine without this.
- [x] Version needs `id >= 32`, else it is considered rfc (explanations in https://github.com/SjonHortensius/3v4l_org/pull/15#discussion_r1690992108)

@SjonHortensius can you provide me with some more guidelines on the above issues? Once I have the project running under docker I will make a pull request with it.

**Comment by SjonHortensius** [comment]
@homersimpsons thanks for your effort. I've been meaning to help someone with this :+1:

* you've found the correct pg library, I'm open to making the dbname dynamic
* in principal I'm not using any bleeding edge features - any pg / fpm / golang / memcached / nginx from the last ~ 5 years should work
* my pg setup isn't special, my hba contains `host	all				all			127.0.0.1/32			md5`
* the nginx setup is supposed to be `root`ed in htdocs while php-fpm runs one level above that
* you are correct - I will update/document how the framework must be included properly - this might not be flexible enough

Please let me know if you need more information - it would be great to get more contributors by getting docker properly setup

**Comment by SjonHortensius** [comment]
thanks for all your work on this! It will definitely make contributing easier for others :+1:
