### ISSUE TITLE
Auto-build of PHP "master" stuck again ?

### ISSUE THREAD

**Issue by jrfnl** [SjonHortensius/3v4l_org#22]
Don't know whether it is kismet or something else, but the daily update of the PHP master for 3v4l seems to be stuck again.

Only a few days so far (August 9th), but the bulk deprecations RFC for PHP 8.4 has just closed with lots of these getting merged now, so kind of unfortunate timing.

Previous conversation about a previous instance of this issue: https://phpc.social/@jrf_nl/112091061544484825

**Comment by SjonHortensius** [comment]
I don't have time at the moment to fix this but the compilation fails with
```
sapi/phpdbg/phpdbg_lexer.l:8:10: fatal error: phpdbg_parser.h: No such file or directory
 #include "phpdbg_parser.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:570: sapi/phpdbg/phpdbg_lexer.lo] Error 1
```

**Comment by jrfnl** [comment]
@SjonHortensius Understood and I honestly wouldn't know how to help. I've check the blame for the `sapi/phpdbg/phpdbg_lexer.l` file, but that hasn't seen any changes since 2022, so it must be something in the `Makefile` I suppose.

**Comment by jrfnl** [comment]
Just looked through the commits from August 9th and the are the ones which look to touch the phpdbg part of PHP. Not sure if it helps, but might give some clue as to what's going on.

* https://github.com/php/php-src/commit/04a67cd86c6b18f04b7f359b2dd3f4daeb6583ac
* https://github.com/php/php-src/commit/9aeb6761b5fcf75dcef6fdbb76fde604beeca6c5
* https://github.com/php/php-src/commit/2e26559fcd8109dd75e68a240a3007ce5c831d3a

The last two commits would also affect PHP 8.2 and 8.3.

**Comment by jrfnl** [comment]
With compliments to @petk :superhero:, it looks like this issue will be fixed once https://github.com/php/php-src/pull/15373 has been merged into PHP Core ! :boom:

**Comment by jrfnl** [comment]
The PR to PHP Core has been merged, so :crossed_fingers: triggering the autobuild manually now (or when it automatically triggers later) should allow for `master` to be up to date again.

**Comment by petk** [comment]
Thanks for reporting issues. Let me know if this fixes your build. I think it should work ok now.

**Comment by jrfnl** [comment]
Closing as fixed, the auto-build has run and 3v4l `master` is up to date again:

![image](https://github.com/user-attachments/assets/208b5d60-1524-4944-97dd-c4cf94425998)
