### ISSUE TITLE
Gracefully handle UTF-8 in Live Preview

### ISSUE THREAD

**Issue by homersimpsons** [SjonHortensius/3v4l_org#8]
It would be a great addition to handle UTF-8 correctly in Live Preview.

I wanted to diagnose some UTF-8 related things but the output is not readable in live-preview: https://3v4l.org/ZsUDp

![image](https://github.com/SjonHortensius/3v4l_org/assets/16977446/985b17ac-b56e-44ba-bffd-54b77d82ac58)
```
string(14) "Î¼ÎµÎ¸Î¿Î´Î¿Ï"
```

Note that it is readable when pressing "eval();" button:
![image](https://github.com/SjonHortensius/3v4l_org/assets/16977446/35e21951-14f4-40da-97e0-59f2a212500d)

Thank you for this awesome project!

**Comment by SjonHortensius** [comment]
this is caused by encoding issues between either the [script>vm](https://github.com/SjonHortensius/3v4l_org/blob/master/htdocs/s/my.js#L253) or [vm>output](https://github.com/SjonHortensius/3v4l_org/blob/master/htdocs/s/my.js#L1100)

**Comment by SjonHortensius** [comment]
@homersimpsons I [rewrote the entire live preview](https://github.com/SjonHortensius/3v4l_org/commit/399346f64492f570c4da9ff2fbfa09a4f7b6011c) last weekend which seems to have fixed this issue - can you confirm?

**Comment by homersimpsons** [comment]
@SjonHortensius Yes it works, thank you!
